# Generated by Django 3.2.11 on 2022-02-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='choose_subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='describe_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
